### ISSUE TITLE
issue: Test API Develop

### ISSUE THREAD

**Issue by jhkim31** [jhkim31/MadPT-server-dev#14]
# Description
실제 API 개발전까지 안드로이드 통신 테스트에 사용될 테스트 API 개발

# Todo
- [ ] 운동 결과 전송 (POST)
- [ ] 음식 리스트 받아오기 (GET)
- [ ] 식단 추가 (POST)
- [ ] 날짜별 운동 기록 받아오기 (GET)
- [ ] 날짜별 식단 데이터 받아오기 (GET)
- [ ] 월별(캘린더) 데이터 받아오기 (GET)
- [ ] 일별 데이터 가져오기 (GET)

# 변경사항
get, post 테스트 url 변경

## get
GET: /api/dev/get
parameter: param:str
response: 
```json
{
    "string": "hello-world",
    "integer": 123,
    "double": 1.23,
    "timestamp": 1650189610288,
    "your_param": "{파라미터값}"
}
```
ex) /api/dev/get?param=123asdf
response:
```json
{
    "string": "hello-world",
    "integer": 123,
    "double": 1.23,
    "timestamp": 1650189610288,
    "your_param": "123asdf"
}
```

## post
POST: /api/dev/post
parameter: None
body:
```json
//어떠한 형식이든 상관 없음 json이기만 하면 됨
{
    "key1" : 123,
    "key2" : "asdf"
}
```
response:
```json
{
    "key_list": [보낸 키값 리스트]
}
```

example:
request body: 
```json
{
    "key1" : 123,
    "key2" : "asdf"
}
```

response:
```json
{
    "key_list": [
        "key1",
        "key2"
    ]
}
```

body로 json 데이터 주면 해당 json 객체에서 key를 뽑아서 리턴

**Comment by jhkim31** [comment]
이 issue는 닫고 새로운 test api issue로 엽니다.
