### ISSUE TITLE
issue: DevOps 스크립트 수정 필요

### ISSUE THREAD

**Issue by jhkim31** [jhkim31/MadPT-server-dev#18]
# Description
CD파트 ec2 배포이후 실행되는 스크립트 
`/Script` 에 있는 
* image_pull.sh
* container_stop.sh	
* new_container_run.sh

파일 수정 필요

# Todo
 
- [x] container_stop.sh 스크립트 수정 
- [x] new_container_run.sh  수정
- [x] image_pull.sh 수정

# Optional Comment
 container_stop.sh는 최대한 빠르게 수정 필요
