### ISSUE TITLE
test api 추가

### ISSUE THREAD

**Issue by jhkim31** [jhkim31/MadPT-server-dev#65]
# Description
5/6 기준 미개발 API에 대한 테스트 API 개발.

# Todo
 
- [x] 목표 저장
- [x] 루틴 저장
- [x] 루틴 불러오기
- [x] 운동 결과 전송
- [x] 일별 운동 기록 조회
- [ ] 월별 데이터 받아오기
- [x] 일별 데이터 받아오기
- [ ] 친구 리스트 가져오기
